[globals]

;these are global variables
DEBUG=3
UI=app/view/|public/|public/js/
AUTOLOAD=app/controller/|app/model/|util/FTS/v12/|api/FTS/v12/
CACHE=true
ESCAPE=false

log_rotation_enabled=1
log_rotate_max_mb=20
log_rotate_max_files=30

dbserver=mysql:host=127.0.0.1;port=3306;dbname=etaxware
dbuser=root
dbpwd_b64=bXlzcWw=
dbpwd=
dbpwd_env=ETAXWARE_DB_PASSWORD
appdeveloper="e-TaxWare Team"
appdevorg="e-TaxWare Team"
applongname="e-TaxWare"