[routes]

;Api routes
POST /=Api->index
GET /=Api->index
POST /testapi=Api->testapi

;products
POST /uploadproduct=Api->uploadproduct
POST /stockin=Api->stockin
POST /stockout=Api->stockout
POST /fetchproduct=Api->fetchproduct
POST /batchstockin=Api->batchstockin
POST /uploadcommoditycode=Api->uploadcommoditycode
POST /batchstockout=Api->batchstockout
POST /stocktransfer=Api->stocktransfer
POST /batchstocktransfer=Api->batchstocktransfer

;invoices
POST /uploadinvoice=Api->uploadinvoice
POST /queryinvoice=Api->queryinvoice
POST /printinvoice=Api->printinvoice

;tin validation
POST /validatetin=Api->validatetin

;check taxpayer
POST /checktaxpayer=Api->checktaxpayer

;query currencies
POST /currencyquery=Api->currencyquery

;credit notes
POST /uploadcreditnote=Api->uploadcreditnote
POST /querycreditnote=Api->querycreditnote
POST /voidcreditnote=Api->voidcreditnote

;debit notes
POST /uploaddebitnote=Api->uploaddebitnote
POST /querydebitnote=Api->querydebitnote

;rate units
POST /loadrateunits=Utilities->loadrateunits

;Email
POST /sendmail=Api->sendmail

;Customer
POST /uploadcustomer=Api->uploadcustomer

;Supplier
POST /uploadsupplier=Api->uploadsupplier

;imported services
POST /uploadimportedservice=Api->uploadimportedservice